#SQL SCRIPT

import sqlite3

dbControl = sqlite3.connect('Pisma.db')
c = dbControl.cursor()

# c.execute('''CREATE TABLE SENDERS
#                 (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT)''')
#
#
# c.execute('''CREATE TABLE USERS
#             (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT)''')
#
#
# c.execute('''CREATE TABLE CASES
#                 (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, TXT_ID TEXT)''')
#
# c.execute('''CREATE TABLE SIGNATURES
#                 (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT)''')
#
#
# c.execute('''CREATE TABLE DOCUMENTS
#                 (ID INTEGER PRIMARY KEY AUTOINCREMENT, SENDER_ID INTEGER, CASE_ID INTEGER, USER_ID INTEGER,
#                 SIGN_ID INTEGER, DESCR TEXT, STATUS_VAL INTEGER, DATE TEXT)''')

c.execute('''DROP TABLE FILES''')

c.execute('''CREATE TABLE FILES (ID INTEGER PRIMARY KEY AUTOINCREMENT, DOC_ID INTEGER, NAME TEXT, FILE BLOB)''')

